### PR TITLE
fix translations on quilt and some updates

### PR DESCRIPTION
**Pull request by tildejustin**
this can wait until after 14.1

Merge base version
- MC Version: 1.16.1
- SpeedRunIGT Version: ~14.1

Changes:
- moved translations to proper directory (does this break automation?)
- optimize translation implementation, fixing quilt as well
- ~~change linux dir from `~/.speedrunigt` to `~/.config/speedrunigt` (addition to #93, should be released together)~~
- ~~updated gradle to 8.5 and regenerated wrapper (can be reverted, I just don't like using outdated tools)~~
- updated ~~loom and~~ mappings
- ~~switched to using built in property substitution for target version~~
- fixed min loader dep to 0.14.20 reflect reality (bumped target to 0.24.25 to avoid having mixinextras at compiletime)

### CODE REVIEW

**Comment by DuncanRuns** [comment]
Lots of files changed here and I have some more changes I want to make for 14.1 so we may see some conflicts

**Comment by tildejustin** [comment]
i'll rebase when you're done

**Comment by tildejustin** [comment]
i have split this commit up into cherrypickable and not cherrypickable commits in order to aid in backporting, and reduced the scale a bit.

**Comment by tildejustin** [comment]
the `~/speedrunigt/` -> `~/.speedrunigt/` -> `~/.config/speedrunigt/` pr will be reverted for the release of 14.1, and i will merge #93 with https://github.com/RedLime/SpeedRunIGT/pull/97/commits/513fe09862c36966a1151732f4d364a4d083853c in a new pr to be merged around when the event system is being backported

**Pull request merged**
